import { describe, expect, it } from 'vitest';
import {
  renderCloudflareRedirects,
  renderNetlifyRedirects,
} from '../src/targets/index.ts';

const sample = {
  'deep-work': {
    url: 'https://www.amazon.com/dp/1455586692?tag=test-20',
    label: 'Deep Work',
  },
  'good-strategy-bad-strategy': {
    url: 'https://www.amazon.com/dp/0307886239?tag=test-20',
    label: 'Good Strategy Bad Strategy',
  },
};

describe('cloudflare target', () => {
  it('emits stable, sorted, 302 lines', () => {
    expect(renderCloudflareRedirects('/go', sample, undefined)).toMatchInlineSnapshot(`
      "# Generated by astro-recommends. Do not edit by hand.
      # basePath: /go
      # entries:  2

      /go/deep-work  https://www.amazon.com/dp/1455586692?tag=test-20  302
      /go/good-strategy-bad-strategy  https://www.amazon.com/dp/0307886239?tag=test-20  302
      "
    `);
  });
});

describe('netlify target', () => {
  it('emits stable, sorted, 302 lines with target-specific header', () => {
    expect(renderNetlifyRedirects('/go', sample, undefined)).toMatchInlineSnapshot(`
      "# Generated by astro-recommends (target: netlify). Do not edit by hand.
      # basePath: /go
      # entries:  2

      /go/deep-work  https://www.amazon.com/dp/1455586692?tag=test-20  302
      /go/good-strategy-bad-strategy  https://www.amazon.com/dp/0307886239?tag=test-20  302
      "
    `);
  });
});
