import type {
  AffiliatesMap,
  ResolvedIntegrationOptions,
} from '../config.ts';

/**
 * Cloudflare Pages _redirects format:
 *
 *   /from/path  https://destination/  302
 *
 * Reference: https://developers.cloudflare.com/pages/configuration/redirects/
 *
 * v0.1: emits one 302 per affiliate slug. Per-entry overrides
 * for status code / rel / target only affect rendered <a> attributes,
 * not the redirect file itself (the redirect just changes the URL).
 */
export function renderCloudflareRedirects(
  basePath: string,
  affiliates: AffiliatesMap,
  _defaults: ResolvedIntegrationOptions['defaults'],
): string {
  const lines: string[] = [
    '# Generated by astro-recommends. Do not edit by hand.',
    `# basePath: ${basePath}`,
    `# entries:  ${Object.keys(affiliates).length}`,
    '',
  ];
  for (const [slug, entry] of Object.entries(affiliates).sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    lines.push(`${basePath}/${slug}  ${entry.url}  302`);
  }
  return lines.join('\n') + '\n';
}
