import type {
  AffiliatesMap,
  ResolvedIntegrationOptions,
} from '../config.ts';

/**
 * Netlify _redirects format:
 *
 *   /from/path  https://destination/  302
 *
 * Reference: https://docs.netlify.com/routing/redirects/
 *
 * Netlify's syntax is a near-superset of Cloudflare's, but it supports
 * `force` flags and a different status comment style. We keep output
 * conservative for v0.1: identical 302 lines, separate header so we can
 * diverge later (e.g. ! force flag, country/role rules) without
 * breaking Cloudflare snapshots.
 */
export function renderNetlifyRedirects(
  basePath: string,
  affiliates: AffiliatesMap,
  _defaults: ResolvedIntegrationOptions['defaults'],
): string {
  const lines: string[] = [
    '# Generated by astro-recommends (target: netlify). Do not edit by hand.',
    `# basePath: ${basePath}`,
    `# entries:  ${Object.keys(affiliates).length}`,
    '',
  ];
  for (const [slug, entry] of Object.entries(affiliates).sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    lines.push(`${basePath}/${slug}  ${entry.url}  302`);
  }
  return lines.join('\n') + '\n';
}
